// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfjA4i3HUrsHwxpk6CS0kE6LyXFuvbGgg',
    appId: '1:487677241251:web:1fd0307924e2bc38f2dc16',
    messagingSenderId: '487677241251',
    projectId: 'faturei-app-dcc3e',
    authDomain: 'faturei-app-dcc3e.firebaseapp.com',
    storageBucket: 'faturei-app-dcc3e.firebasestorage.app',
    measurementId: 'G-HMCMNREQG2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFmnibv-eOfbJud3vZlJpJqJ1zhnJX2Jc',
    appId: '1:487677241251:android:f8ccfdcea8ddbb85f2dc16',
    messagingSenderId: '487677241251',
    projectId: 'faturei-app-dcc3e',
    storageBucket: 'faturei-app-dcc3e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLcYeRNvcyr5N0vGIJfgUt3gsvJkvJLe8',
    appId: '1:487677241251:ios:e917f3dbc066775ff2dc16',
    messagingSenderId: '487677241251',
    projectId: 'faturei-app-dcc3e',
    storageBucket: 'faturei-app-dcc3e.firebasestorage.app',
    iosBundleId: 'com.example.flutterCurso',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLcYeRNvcyr5N0vGIJfgUt3gsvJkvJLe8',
    appId: '1:487677241251:ios:e917f3dbc066775ff2dc16',
    messagingSenderId: '487677241251',
    projectId: 'faturei-app-dcc3e',
    storageBucket: 'faturei-app-dcc3e.firebasestorage.app',
    iosBundleId: 'com.example.flutterCurso',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfjA4i3HUrsHwxpk6CS0kE6LyXFuvbGgg',
    appId: '1:487677241251:web:b5a7a15b93b4f5a6f2dc16',
    messagingSenderId: '487677241251',
    projectId: 'faturei-app-dcc3e',
    authDomain: 'faturei-app-dcc3e.firebaseapp.com',
    storageBucket: 'faturei-app-dcc3e.firebasestorage.app',
    measurementId: 'G-B89GY3VG6M',
  );
}
